### ISSUE TITLE
Mask() painfully slow

### ISSUE THREAD

**Issue by netpalantir** [Intervention/image#1031]
Hello,

I have this scenario:

    $thumb = Image::make($fullName);
    $thumb->insert($maskName);
    $thumb->mask($maskInverted);

I am opening a jpg file (fullName), then I am overlaying it with a PNG, and then I am applying another PNG as a mask. All the images have the same size (156x171px).
If I comment out line 3, the server responds immediately.
If I leave line 3, then the server takes over 25 seconds to respond.

Am I doing anything wrong, is this expected, or did I hit a bug?

Using PHP 7.2 and Intervention Image 2.5.1.

Thanks!

**Comment by mfn** [comment]
Disclaimer: I know nothing specifically about this feature, I just looked at the source

Are you using the GD or Imagick driver?

I'm asking because the GD MaskCommand seems to do a lot of things manually with pixels, see https://github.com/Intervention/image/blob/8ee5f346ce8c6dcbdc7dec443486bd5f6ad924ff/src/Intervention/Image/Gd/Commands/MaskCommand.php#L41-L75

In contrast, the Imagick one doesn't have such code.

Just a hunch, sorry if its unrelated!

**Comment by netpalantir** [comment]
Yes, this totally solved my problem! Maybe we could mention this in the mask() documentation page? I was not aware of this limitation of GD.

Thank you for your help!
