### ISSUE TITLE
Imagecache abandoned

### ISSUE THREAD

**Issue by driesvints** [Intervention/image#1280]
Hi there, I hope I don't overstep here by opening this issue. I noticed https://github.com/Intervention/imagecache is abandoned but I couldn't find any steps to migrate away from it. Do we need to migrate to new functionality in the image library here? Or is the library simply abandoned without a replacement? Would be good to have a small explanation of that in the readme of https://github.com/Intervention/imagecache 🙂

**Comment by olivervogel** [comment]
I'm sorry, but at the moment there is no quick and easy replacement or other functionality.

There are three main reasons why I will no longer work on it.

- Unfortunately, I have not been able to make any real progress in the last few years, even though I would have liked to. That's why it's better for me to finally end the project than not to deal with any issues or pull requests.
- My time is unfortunately very limited and I prefer to focus on `intervention/image` support as my main task.
- My impression was that most people use [Glide](https://glide.thephpleague.com/) rather than `intervention/imagecache` anyway, which was another reason to (officially) stop supporting it.

**Comment by driesvints** [comment]
Hi @olivervogel. Thank you so much for taking the time to explain that. That's all perfectly understandable and reasonable. All the best of luck with your other endeavours 🙂
