### ISSUE TITLE
256MB exhausted on "read" a 5MB image

### ISSUE THREAD

**Issue by christoferd** [Intervention/image#1310]
**Describe the bug**
Intervention (with GD driver) using too much memory to read a 5MB jpg file.

**Code Example**
$manager->read($filePathTo5MBjpg)

**Expected behavior**
Expect the system to read the file as there is 256MB allocated to PHP.

**Images**
Not applicable. It's a normal photo taken on phone with Android OS

**Environment (please complete the following information):**
 - PHP Version: 8.2 (local development)
 - OS: Windows
 - Intervention Image Version: 3.4.0
 - GD or Imagick: GD

**Comment by olivervogel** [comment]
Unfortunately, memory consumption with the GD library is a recurring problem.

With the GD library, you cannot directly equate the file size with the memory consumption. GD unfortunately consumes much more; for an image with 4000x3000 pixels, RGB, 8 bits per channel, for example, you have to allocate about 50 MB just to get it into memory, even if it only takes up about 2-3 MB on the hard disk. Each manipulation requires additional disk space.

In the `read()` function, in addition to reading the image, the EXIF data is also extracted (for the Jpeg format) and, depending on that, an alignment (rotate/flip) is performed, both of which continue to consume memory.

I recommend using Intervention/Image with Imagick if you are working with large images. It is much more memory efficient.

PS: I don't like to play the "works-on-my-machine" card, because I know it does not help, but I just did a quick test in my environment and read in the following [5.2 MB JPG image](https://upload.wikimedia.org/wikipedia/commons/2/2d/Snake_River_%285mb%29.jpg). Which worked without any problems, even with 128MB memory limit.

#### Environment

- PHP Version: 8.3.2
- OS: MacOS
- Intervention Image Version: 3.4.0
- GD or Imagick: GD

**Comment by christoferd** [comment]
Okay, thanks, will use Imagick
