### ISSUE TITLE
Support for setting the Least Significant Bit (LSB)

### ISSUE THREAD

**Issue by Elycin** [Intervention/image#1352]
**Describe the feature you'd like**
Simply put, a way to set the LSB.

There are solutions that exist that can be called directly with the core drivers, but I feel like having that easy abstraction in the library could be a nice touch.

**Is your feature request related to a problem? Please describe.**
I work on projects for content creators where a common issue in the industry is preventing unauthorized use or stealing content, having the capability to encode some data that could be used to identify sources of where material was copied from would be useful.

**Comment by olivervogel** [comment]
Thanks for sharing that idea. I think it's an interesting feature, and I've actually thought about including it several times. However, I think that due to the added complexity and the rather niche nature of the feature, steganography is better placed in a package separate from this library. This can of course use the capabilities of Intervention Image and integrate it as a dependency.
