### ISSUE TITLE
Resizing some gifs results in missing frames

### ISSUE THREAD

**Issue by GuySartorelli** [Intervention/image#1380]
## Describe the bug

https://i.pinimg.com/originals/60/5f/6a/605f6ab7beccce2cb2083f97d013445a.gif

Resizing the above linked gif results in an image that is missing several frames, as seen in the "Images" section below.

## Code Example

```php
<?php

$autoload = 'vendor/autoload.php';
if (!file_exists($autoload)) {
    echo 'autoload file is missing - make sure you ran `composer install`.' . PHP_EOL;
    exit(1);
}
include_once $autoload;

use Intervention\Image\ImageManager;
use Intervention\Image\Drivers\Imagick\Driver;

// create new manager instance with desired driver
$manager = new ImageManager(new Driver());

// read image from filesystem
$image = $manager->read('605f6ab7beccce2cb2083f97d013445a.gif');

// scale and save result
$image->scale(300)->save('resizedimage.gif');
```

## Expected behavior

The result of the resize should be a gif of the correct size with no missing frames.

## Images
![resizedimage](https://github.com/user-attachments/assets/648b4fb6-f603-4da9-80e3-912053209e0a)

## Environment (please complete the following information):
 - PHP Version: Only tested with 8.2
 - OS: Ubuntu 22.04
 - Intervention Image Version: Only tested with 3.7.2
 - GD or Imagick: Only tested with Imagick

**Comment by olivervogel** [comment]
Thanks for reporting, Guy. I will look into this.

**Comment by olivervogel** [comment]
I took a look at your result image. The input has 300 frames, which took a while to process but the output has the same frame count. However, from number 55 onwards, the individual frames are only repeated.

Unfortunately, I cannot reproduce the strange behavior on my machine at the moment. However, I have two ways to narrow down the issue further and get more information.

### 1. Check Imagick / ImageMagick Version

I would ask you to check which version of Imagick and ImageMagick is responsible for the faulty result and post it here.

I tested this successfully with:

- PHP `8.2.20`
- `imagick module version 3.7.0`
- `ImageMagick 7.1.1-18 Q16-HDRI aarch64 21582 https://imagemagick.org `

as well as

- PHP `8.3.8`
- `imagick module version 3.7.0`
- `ImageMagick 7.1.1-27 Q16-HDRI aarch64 21931 https://imagemagick.org`

### 2. Resize with Imagick only

Furthermore, you can check if you get the same result with the following code, which corresponds to the logic that is run by Intervention Image under the hood.

```php
$imagick = new Imagick();
$imagick->readImage('605f6ab7beccce2cb2083f97d013445a.gif');
$imagick = $imagick->coalesceImages();

foreach ($imagick as $frame) {
    $frame->scaleImage(300, 225);
}

$format = 'gif';
$compression = Imagick::COMPRESSION_LZW;

$imagick->setFormat($format);
$imagick->setImageFormat($format);
$imagick->setCompression($compression);
$imagick->setImageCompression($compression);

$blob = $imagick->getImagesBlob();

file_put_contents('resizedimage.gif', $blob);

```

**Comment by GuySartorelli** [comment]
Imagick version: `3.7.0`
ImageMagick version: `6.9.11-60 Q16 x86_64 2021-01-25`

Still get the same results when running with that sample code. Looks like the difference here might be the version of ImageMagick... looks like Ubuntu doesn't have 7.x available via `apt` 😮‍💨

For the sake of completion I double checked with GD and that _does_ process the gif correctly.

**Comment by olivervogel** [comment]
I have integrated the conversion into a [GitHub workflow](https://github.com/Intervention/image/pull/1382/files) to make the results of different version combinations comparable.

As it turns out, all results are fine.


### PHP 8.1 - ImageMagick 6.9.12-55

https://github.com/Intervention/image/actions/runs/10078050180/artifacts/1735244634

### PHP 8.1  ImageMagick 7.1.1-32

https://github.com/Intervention/image/actions/runs/10078050180/artifacts/1735245815

### PHP 8.2 - ImageMagick 6.9.12-55

https://github.com/Intervention/image/actions/runs/10078050180/artifacts/1735248028

### PHP 8.2 - ImageMagick 7.1.1-32

https://github.com/Intervention/image/actions/runs/10078050180/artifacts/1735246759

### PHP 8.3 - ImageMagick 6.9.12-55

https://github.com/Intervention/image/actions/runs/10078050180/artifacts/1735244683

### PHP 8.3 - ImageMagick 7.1.1-32

https://github.com/Intervention/image/actions/runs/10078050180/artifacts/1735248309


Unfortunately, the error is currently not reproducible for me and does not appear to be caused by Intervention Image, as your run of the sample code has shown.

**Comment by GuySartorelli** [comment]
Huh, weird.... A colleague of mine discovered it on their machine and I replicated it so it's not unique to me, but as you say it's clear it's not specific to intervention/image.
Thanks for looking into this.

**Comment by olivervogel** [comment]
Yes, that's really weird. I also [checked](https://github.com/Intervention/image/pull/1382/files) the ImageMagick version `6.9.11-60 Q16 x86_64 2021-01-25 ` with Imagick `3.7.0` you used and got correct results here as well.

### PHP 8.1 - ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25

https://github.com/Intervention/image/actions/runs/10093351057/artifacts/1739176051

### PHP 8.2  ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25

https://github.com/Intervention/image/actions/runs/10093351057/artifacts/1739175668

### PHP 8.3  ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25

https://github.com/Intervention/image/actions/runs/10093351057/artifacts/1739175712

**Comment by GuySartorelli** [comment]
Thank you for the investigation! I've just had a last thought. We know this isn't caused by this library now so feel free to say no, but would you be willing to try it using [DDEV](https://ddev.com/)?

That's what I use for local development most of the time and I can reproduce my results using it. It's powered by docker so hopefully that means you would get the same results that I do.

You could just run `ddev config --auto` to set up the environment, then `ddev start` to spin up the containers and `ddev exec 'php run.php'` to run the code.

**Comment by olivervogel** [comment]
Yes, with ddev I also get an **incorrect result**. I still can't explain the error, especially since I got correct results with exactly the same ImageMagick version in a different environment. 

![resizedimage](https://github.com/user-attachments/assets/12aef6e8-badf-4901-babf-be5717d13ab1)

- ddev Version: `v1.23.3`
- PHP: `8.2.20`
- Imagick: `3.7.0`
- ImageMagick: `ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org`

**Comment by GuySartorelli** [comment]
Thank you, that at least gives me something to work with to try figure out what's going wrong here 👍
