### ISSUE TITLE
support webp image

### ISSUE THREAD

**Issue by thnt** [Intervention/image#233]
any plan to support webp image from Google?

**Comment by philippzentner** [comment]
Any progress here?

**Comment by razor2611** [comment]
Any news on this? We really need webp support.

**Comment by garygreen** [comment]
Should be very easy to add support for webp.... Imagick support it and also [GD](http://php.net/manual/en/function.imagewebp.php)

**Comment by abhimanyusharma003** [comment]
:+1:

**Comment by philokezzar** [comment]
+1 for webp support please

**Comment by Teranode** [comment]
anything on this?

**Comment by olivervogel** [comment]
The problem is, support for WebP is only half-baked in GD and Imagick. And an implementation into Intervention Image would be only possible with hacks and workarounds.

For a better understanding I listed some of the issues. GD has `imagewebp()` and `imagecreatefromwebp()` bit apparently lacks support with other functions Intervention Image uses.

## GD issues

- `getimagesize()` does not recognize webp format
- There is no official mime type for WebP and GD function `image_type_to_mime_type()` does not recognize WebP

## Imagick issues

- Is only supported if Imagick is rebuilt with an additional webp library.

## General issues

- PHP Fileinfo extension can't read WebP inofficial mime type

**Comment by paslandau** [comment]
Is there any viable way to work around this limitation? I wouldn't mind calling any native PHP functions - just wondering if anyone has already done this and would like to share :)

Cheers
Pascal

**Comment by ifox** [comment]
Any update on this ?

**Comment by mkwsra** [comment]
:+1:

**Comment by blueset** [comment]
Looking forward for support with WebP.

**Comment by abhimanyu003** [comment]
@olivervogel any plans on adding `webp` support in 3.0 at least for `imagick` users ?

**Comment by hanspagel** [comment]
would love to have webp in intervention/image, even if not all features are supported yet

**Comment by paulocastellano** [comment]
+1

**Comment by tma-dathi** [comment]
+1

**Comment by bokideckonja** [comment]
+1

**Comment by bokideckonja** [comment]
Any update on this?

**Comment by anik786** [comment]
+1

**Comment by megalogi** [comment]
+1

**Comment by d3x773r** [comment]
+1

**Comment by websitevirtuoso** [comment]
+1
