### ISSUE TITLE
MaskCommand - Hangs with fatal error

### ISSUE THREAD

**Issue by lakshmana** [Intervention/image#414]
Everytime I use the mask command, I have this timeout fatal error " Fatal error: Maximum execution time of 120 seconds exceeded in ....\vendor\intervention\image\src\Intervention\Image\Commands\Argument.php on line 130".

The problem seems to occur from Intervention\Image\Gd\Commands\MaskCommand.php line no. 43 & 44 that reads ""$color = $image->pickColor($x, $y, 'array');
$alpha = $mask->pickColor($x, $y, 'array');"

**Comment by olivervogel** [comment]
Due to the limitations of GD, the `mask()` method must read every pixel individually and is not very efficient. If you're masking large images, this can take some time. In your case I would try to increase the max. execution time with [ini_set](http://php.net/manual/en/function.ini-set.php).

**Comment by graphicgeek** [comment]
I was having trouble with the mask command freezing up as well. I found that using the imagick driver instead of the default gd driver fixed the issue.

Just go into config/image.php and change:

'driver' => 'gd'

to

'driver' => 'imagick'

You'll also need to make sure ImageMagick is installed:

sudo apt-get update && sudo apt-get install -y imagemagick php5-imagick && sudo service php5-fpm restart

**Comment by lakshmana** [comment]
Hi graphicgeek, Thanks for the reply.  
But I have no control on the server and so could not use Imagick driver. :( I solved the probem with HTML canvas js.
