### ISSUE TITLE
Working with Laravel 5.1, response() doesn't work

### ISSUE THREAD

**Issue by Madnx** [Intervention/image#430]
I'm using Laravel 5.1.17 and the 2.3 versions of Image and response() seems to send invalid images to the browser. Any idea?

**Comment by olivervogel** [comment]
Any error message?

**Comment by codel** [comment]
No error. It works fine when I save it to the server but any image created can't be sent to the browser. Firefox tells me that the image simply contains errors.

**Comment by olivervogel** [comment]
Sorry, can't help without additional information.

**Comment by codel** [comment]
I'm going to look in laravel log but I was here to check if anyone had the same issue.

**Comment by olivervogel** [comment]
Any information would help. Code examples, log infos, error messages, screenshots. I can't just remote debug your app, if the only information is "it does not work".

**Comment by codel** [comment]
Never mind. Seems  to be an issue only with me and Response:

```
$response = \Response::make(\Storage::disk('public')->get("img/logo.png"));
$response->header('Content-Type', 'image/png');
return $response;
```

Doesn't even work.

**Comment by koichirose** [comment]
I was opening an issue but found this one.
I have the same issue and it's very weird:
```php
Image::configure(array('driver' => 'imagick'));
$img = Image::cache(function($image) use ($image_path) {
	$image->make($image_path)->fit(50, 50);
}, 43200, true);
echo $img->response('jpg);
```

The code above won't work.
Firefox says the image contains errors, Chrome says ERR_CONTENT_DECODING_FAILED.

Changing the size to 105x105 or above works. 104x104 and below doesn't. The required minimum size is different for each image (I tried a couple, the minimum limit for another one was 129x129).
It looks that one dimension above the limit is enough (128x129 works).
It works on one machine though, and not on another.
Works: PHP Version 5.5.26 - imagick module version 3.1.2 - OS X 10.11
Doesn't work: PHP Version 5.5.15-1 - imagick module version - 3.1.2 - Ubuntu 14.04.3 LTS

It doesn't seem Laravel-related since I'm using it on a Codeigniter installation.

Hope I provided enough information to help you debug this, tell me if you need anything else :)

**Comment by koichirose** [comment]
Hello, is there any update about this?
Thank you
