### ISSUE TITLE
Scaling algorithm

### ISSUE THREAD

**Issue by atayahmet** [Intervention/image#504]
Hi everyone,

can i prefer algorithm when image scaling? (IMG_BICUBIC, IMG_BICUBIC_FIXED etc.)

As examples of the links below
http://php.net/manual/en/function.imagesetinterpolation.php

Thank you.

**Comment by olivervogel** [comment]
You can access the GD resource with [getCore()](http://image.intervention.io/api/getCore) and apply any addition function you like.

**Comment by DeepDiver1975** [comment]
This does not work because in the ResizeCommand a new image is create $modified - see https://github.com/Intervention/image/blob/8ee5f346ce8c6dcbdc7dec443486bd5f6ad924ff/src/Intervention/Image/Gd/Commands/ResizeCommand.php#L47
There is no possibility for the api caller to access the GD resource of $modified.

Mind reopening this issue @olivervogel ? THX
