### ISSUE TITLE
Intervention / image with CakePHP 2.x

### ISSUE THREAD

**Issue by rifton007** [Intervention/image#506]
Hello, I would use my application with CakePHP 2.x
I install composer.phar since my app folder.
Then I install Intervention / image. Which is now in my app / vendor folder.

I load every plugin: CakePlugin::Loadall ().

But I can not charge the ImageManager class.

Thank you,

**Comment by olivervogel** [comment]
I never used CakePHP, can't help you here.

**Comment by drmonkeyninja** [comment]
I know that this issue is a little old, but thought it was worth commenting in case anyone else arrived here via Google like I did.

@rifton007 using `CakePlugin::loadAll()` will make no difference as that will only load CakePHP plugins, which Intervention isn't. You need to follow the [installation steps](image.intervention.io/getting_started/installation) and make sure your CakePHP app is set up to load Composer packages. We use the following in CakePHP's bootstrap.php file to ensure autoload is happening:-

```php
// include the composer autoload
if (file_exists(ROOT . DS . 'Vendor' . DS . 'autoload.php')) {
	require_once ROOT . DS . 'Vendor' . DS . 'autoload.php';
	spl_autoload_unregister(array('App', 'load'));
	spl_autoload_register(array('App', 'load'), true, true);
} else {
	die('Composer install has not yet been run.');
}
```
