### ISSUE TITLE
Create round image

### ISSUE THREAD

**Issue by kamov** [Intervention/image#539]
Hi,
how to create round image with canvas and transparent background?
Thanks!

**Comment by JHGitty** [comment]
I think there is currently no way to create round images.

**Comment by kamov** [comment]
Yes, I know about border-radius: 50% make round, but is not cross browser.
There is way with php, so I guess how to do this with intervention/image...

**Comment by JHGitty** [comment]
Could you provide us a solution for Imagick *and* GD? If yes we could integrate it directly into Intervention/Image.

**Comment by kamov** [comment]
I make a quick searching and I found below, I don't test but seem working fine:
GD:
http://stackoverflow.com/questions/9880503/crop-image-in-circle-php
Imagick:
http://stackoverflow.com/questions/999251/crop-or-mask-an-image-into-a-circle

**Comment by bohrasd** [comment]
It's simple in Imagick to use the roundCorners() function to create a round image.
But I cant find a way in GD.

**Comment by olivervogel** [comment]
You can use [mask()](http://image.intervention.io/api/mask) with a round alpha mask.

**Comment by subdesign** [comment]
I found a working example I used: https://www.imnobby.com/2022/06/02/php-crop-image-from-square-to-circle-aka-set-image-border-radius/

only the the below line did not work, gave error like "Image source not readable"
```$resized_img = Image::make($img->response('png')); ```

if I replace the parameter with the image object, it will work: 
```$resized_img = Image::make($img);```

If you insert the masked image into a bigger background image, the circle image won't have square edges because of the mask, you know what I mean..

<img width="185" alt="Screenshot 2024-04-04 at 11 37 19" src="https://github.com/Intervention/image/assets/691695/18230d56-55ef-4049-8e23-94f961edc3a6">
