### ISSUE TITLE
write on image from right to left (Arabic) support 

### ISSUE THREAD

**Issue by imadsh** [Intervention/image#630]
Hi , 
Is there is any way to write on image from right to left like arabic  ?? ? 
i got this problem today and i dont know how to fix this 

anyone can help please ? ? 

problem example 
https://s9.postimg.org/sb4ozo1un/download.jpg
i expect like 
https://s22.postimg.org/ftk5pmyup/download.jpg

**Comment by haakym** [comment]
To add more detail to the issue:

- Letters should be written from right to left - they are currently going from left to right
- Letters are not being joined up, certain letters have different forms based on what letter precedes of follows them or lack thereof - they are currently only showing their singular form (i.e. not joined), this may however just be because of the first RTL issue?

**Comment by 8lbiasian** [comment]
i solve this issue by following 

install the Ar-PHP Library 

then do the following 

`
        $Arabic = new I18N_Arabic('Glyphs');
        $name = $Arabic->utf8Glyphs($student->name_ar);
        $img->text($name, 800, 220, function ($font) {
            $font->file('fonts/trado.ttf');
            $font->size(40);
            $font->align('right');
        });
`

i try both font trado and arial and work perfectly.

**Comment by abdullah-abunada** [comment]
how are you installed Ar-PHP Library in Laravel ??

**Comment by haakym** [comment]
@abdullah-abunada 

https://github.com/Johntaa/ar-php

I guess by composer?

**Comment by abdullah-abunada** [comment]
thanks its work very well
