### ISSUE TITLE
Color Profile Issue, can't seem to find the solution. Washed out images with imagick (or gd).

### ISSUE THREAD

**Issue by tobiasvielmetter** [Intervention/image#707]
Hi,
I saw that this issue has been discussed several times before and has been either dismissed or was specific for one kind of conversion.

Here is the scenario:
I have users uploading images of artwork in their accounts to display. I use image intervention through thephpleague/glide in order to display the images in different sizes. The original images can be in different formats and may have different profiles, I cannot ask my users to prepare the images fro web in sRGB.

I am using the imagick driver (have tried gd before, which was worse).

I have a simple example with a jpg image with adobe RGB 1998 as profile. This image comes out slightly washed out, most colors are a little dull.
If I save the image in photoshop with sRGB before upload all is fine. Just when I upload an image with the adobe profile it looks washed out. Other, more exotic profiles might look completely off.

Anyhow, as far as I understand: The image is stripped from its profile and not converted to the default sRGB profile before this happens. I dont necessarily undertsand how this is a good practice. Is there any way I could implement conversion? Obviously if the colors would be properly mapped between the profiles before the profiles are stripped the image coloration wouldn't be so off. Or am I missing something?

For now for my own purpose I have included the following procedure before giving an image to image intervention, which fixes the issue:

```
        //make sure image is properly converted to srgb
        //inspired by https://github.com/mosbth/cimage/blob/master/CImage.php#L2552
        $image      = new \Imagick($tmp);
        $colorspace = $image->getImageColorspace();
        $profiles      = $image->getImageProfiles('*', false);
        $hasICCProfile = (array_search('icc', $profiles) !== false);
        if ($colorspace != \Imagick::COLORSPACE_SRGB || $hasICCProfile) {
            $sRGBicc = file_get_contents(base_path('resources/icc/sRGB_IEC61966-2-1_black_scaled.icc'));
            $image->profileImage('icc', $sRGBicc);
            $image->transformImageColorspace(\Imagick::COLORSPACE_SRGB);
            $image->writeImage($tmp);
        }
```

All best,
T

**Comment by notflip** [comment]
Did you ever find a solution to this? I have the exact same problem.

**Comment by tobiasvielmetter** [comment]
@notflip I don't think image intervention has a standard solution for this for now and phpleague/glide is just basing this on image intervention... I would recommend using something along the lines of code I have presented in my original post as work around, it certainly fixed the issue for my purpose. Also check https://github.com/mosbth/cimage/blob/master/CImage.php#L2552, which I based my solution on. They have the proper color profile at https://github.com/mosbth/cimage/tree/master/icc.

**Comment by notflip** [comment]
Thanks I'll give it a try, I'm also using Glide so I thought the problem was there but they obviously only serve the images. Thanks a lot!

**Comment by mindplay-dk** [comment]
@olivervogel any idea if we can do something about this?

Our old (proprietary) image library was hard-coded against Imagick to deal with this issue.

I could implement something similar as a Command, but then it's so-long to GD support, as it doesn't have any features for color management.

Unless perhaps what GD does already is convert to a standard RGB color profile?

I have no idea.

It wouldn't make much sense if it merely strips and ignores the color profile?

Though I suspect that's exactly what it does, since our legacy image library uses primarily GD, but internally uses Imagick to convert from other color profiles to standard RGB - I guess whoever resorted to doing this had a reason to do so.

Is there anything we can do?

**Comment by mindplay-dk** [comment]
My thinking thus far, after talking to a coworker: GD merely strips color profiles without conversion, so the behavior of the Decoder implementations is already inconsistent - we don't currently have feature/behavior parity between the two drivers in this regard.

If it's already inconsistent, we're not making it worse by fixing the behavior of the Imagick Decoder?

By fixing it, I mean, make the Decoder automatically convert to sRGB, rather than preserve the color profile (the current, default behavior) which is how images are generally delivered on the web.

Make sense?

**Comment by tobiasvielmetter** [comment]
@mindplay-dk I would agree with this. Just because gd is limited, it shouldn't hold back the imagick driver to implement reasonable default behaviour. Stripping profiles is never a good solution and basically messes up the image beyond repair, as nobody knows afterwards what the original profile was. In environments where somewhat accurate color reproduction counts, this is simply not an acceptable solution and I couldn't think of an environment were it makes sense to put this burdon on the user (eg please convert all your images into sRGB profile before uploading). 
You can see that most image services such as imgix.com or googles getImageServingUrl in app engine do exactly that: they convert to sRGB to keep a reasonable color reproduction after manipulation.

**Comment by mindplay-dk** [comment]
Well, here's a preliminary implementation - I referenced our legacy implementation and cross-referenced with CImage.

It supports two use-cases we commonly encounter in-house:

1. There's an *embedded* profile: in this case, convert to sRGB color space and remove the profile
2. The image uses a CMYK profile which *isn't* embedded: load a built-in CMYK profile and convert to sRGB

The "test" currently dumps the resulting images for those two use-cases into the `tests/tmp` folder, where you can visually examine the results, e.g. by opening the images in browser tabs, then tab back and forth - or open them in Photoshop and confirm using the color picker, etc.

GD mangles both images, as expected, and Imagick now properly converts in both cases.

Works for me. But I have no idea how to write a real integration test for this.

Thoughts?

**Comment by mindplay-dk** [comment]
@olivervogel can you let us know if you're interested in this feature?

If not, I will create a separate package with an extended Imagick Decoder.

**Comment by mindplay-dk** [comment]
@olivervogel can you please let me know if you're interested in this feature?

Our users expect parity with the legacy system, so we can't launch until this is resolved, one way or the other - if I don't hear from you, I'm going to assume you're not interested, and I'll release a separate package with an extended decoder for Imagick...

**Comment by mindplay-dk** [comment]
For the record, I'm not pursuing this issue any further. We've hard-coded the solution into our own system, which ultimately we decided will only be supported on systems with Imagick installed.

I assume the reason the author doesn't respond, is because he insists of feature parity between the GD and Imagick back-ends, which is understandable. It's a shame that GD, being the standard image library in PHP, has to be the lowest common denominator, but we can't really fault this package for that.

**Comment by bividesign** [comment]
@tobiasvielmetter Thank you! Your solution to this is just what I needed to find. I am facing the exact issue, users uploading artwork, and saying "please convert your images to sRGB" is NOT an option.

**Comment by olivervogel** [comment]
Version 3 of Intervention Image [supports color profiles](https://image.intervention.io/v3/basics/colors#color-profiles) with the Imagick driver.  For example, it is now possible to load a PNG file with an Adobe RGB color profile and output it in Jpeg format, whereby the Adobe color profile is retained and also embedded in the Jpeg.

Unfortunately, it is still not possible to interpret color profiles with the GD library and therefore also not with Intervention Image and the driver for this library
