### ISSUE TITLE
Unable to init from given url (url which exists and I can access via browser ).

### ISSUE THREAD

**Issue by stelasido** [Intervention/image#958]
Hi, I am getting images from remote address and save them in local. Everything works fine. I have allow_url_fopen enabled and  I can access the url which is `http`. The problem is when I put that code in a queued job, then in the logs I see this error:

>  local.ERROR: Unable to init from given url
I can't understand, because the same code works without queued job, but inside it don't.
The code is simple:

`				      try{
                                        // $photo->url exists
					$img = Image::make($photo->url);

					// SAVE BIG IMAGE
					$img->save($path . $filenameBig);

				}catch (Intervention\Image\Exception\NotReadableException $e){
					var_dump($e->getMessage());
				}`

**Comment by stelasido** [comment]
I even changed the URL to some of online fake image generators. The result is the same

**Comment by Yakubina** [comment]
Same for me. Image URL is valid, but can't process it with this library

**Comment by DylanGD** [comment]
Same here... URL is valid but can't be processed

**Comment by idmahbub** [comment]
apparently I'm not alone

**Comment by dimdam** [comment]
Anyone solved this one?

**Comment by PatricNox** [comment]
Same issue here

**Comment by PatricNox** [comment]
I've digged in this since I myself have the very same problem as above. 

I've found that the issue relies on the PHP file_get_contents getting a timeout whilst trying to retrieve the input file. 

> failed to open stream: Connection timed out

This means that the PHP instance gets timed out, obviously. Reason can be too big of a file, the PHP container is restricted to curl from external resources or just a firewall blocking. 

You can verify the latter by increasing `default_socket_timeout` and then run it again. This will show if it's a firewall/restriction: 


> file_get_contents(blablabla): failed to open stream: Connection refused

**Comment by olivervogel** [comment]
The integration of the option to read data directly via URLs was a mistake. The task of this library is image manipulation. Reading data via HTTP should be done by a corresponding client. For this reason, Intervention Image Version 3 does not support reading URLs.
