### ISSUE TITLE
INTERVENTION IMAGE - Running Composer returns: “Could not open input file: composer.phar”

### ISSUE THREAD

**Issue by SEMHussain** [Intervention/image#972]
When i install the -php composer.phar require intervention/image- this library i got the this error, Could not open input file: composer.phar, im very tired and very upset, wahy this all errors are only come to m2 ? what i do ? who can help me please 
![Screenshot (9)](https://user-images.githubusercontent.com/19269959/65407258-9227ed80-ddff-11e9-8000-1ed221d20ca0.png)

**Comment by KEINOS** [comment]
@SEMHussain 

Can't tell you much but I think there's something wrong with `composer.phar` rather than the `intervention/image` package.

Maybe you are missing access privileges to the directory such as `./vendor` dir or `~/.composer` at your home dir.

Check if the `diagnose` command gets you something. 

```
C:\\Users\LAKMAL SIR\Desktop\LARAVEL\semh>php composer.phar diagnose
```
- See [diagnose](https://getcomposer.org/doc/03-cli.md#diagnose)

Or maybe you need to update.

```
C:\\Users\LAKMAL SIR\Desktop\LARAVEL\semh>php composer.phar update
```

Good luck. 🤞
